//! Pure filename generation, title normalization, and metadata recovery.
//!
//! This module never performs I/O. It accepts verified domain values, produces one safe filename
//! component, and parses only the filename contract produced by this module.

use crate::{
    domain::{DomainError, EpisodeRef, MediaType, TmdbId, TmdbItem, VideoExtension},
    error::NamingError,
};

/// Conservative maximum filename-component size used by the cross-platform naming contract.
pub const MAX_FILENAME_BYTES: usize = 255;

const REPLACEMENT_SEPARATOR: &str = " - ";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PendingSeparator {
    None,
    Space,
    Replacement,
}

/// A parsed reference recovered from a filename generated by this module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedMediaReference {
    /// The positive TMDB identifier encoded in the filename.
    pub tmdb_id: TmdbId,
    /// The media namespace inferred from the filename shape.
    pub media_type: MediaType,
    /// The season number for a series filename, or `None` for a movie.
    pub season: Option<u32>,
    /// The episode number for a series filename, or `None` for a movie.
    pub episode: Option<u32>,
    /// The normalized title retained as a display hint.
    pub title_hint: String,
    /// The canonical lowercase source-video extension.
    pub video_extension: VideoExtension,
}

impl ParsedMediaReference {
    /// Returns the parsed series episode, when this is a series reference.
    pub fn episode_ref(&self) -> Option<EpisodeRef> {
        self.season
            .zip(self.episode)
            .map(|(season, episode)| EpisodeRef::new(season, episode))
    }

    /// Returns the parsed extension without its leading period.
    pub fn extension(&self) -> &str {
        self.video_extension.as_str()
    }
}

/// Normalizes a TMDB title into one deterministic, filesystem-safe filename component.
///
/// This function deliberately applies the invalid-character policy on every platform, including
/// platforms that permit some of those characters. It preserves the raw title only in the caller;
/// the returned value is suitable for the title component of a generated filename.
pub fn normalize_title_for_filename(raw_title: &str) -> Result<String, NamingError> {
    let mut normalized = String::new();
    let mut pending_separator = PendingSeparator::None;

    for character in raw_title.trim().chars() {
        if is_invalid_title_character(character) {
            pending_separator = PendingSeparator::Replacement;
            continue;
        }

        if character.is_whitespace() {
            if !normalized.is_empty() && pending_separator != PendingSeparator::Replacement {
                pending_separator = PendingSeparator::Space;
            }
            continue;
        }

        if !normalized.is_empty() {
            match pending_separator {
                PendingSeparator::None => {}
                PendingSeparator::Space => normalized.push(' '),
                PendingSeparator::Replacement => normalized.push_str(REPLACEMENT_SEPARATOR),
            }
        }
        normalized.push(character);
        pending_separator = PendingSeparator::None;
    }

    trim_trailing_filename_noise(&mut normalized);
    if normalized.is_empty() {
        return Err(NamingError::EmptyTitle);
    }

    if is_windows_reserved_name(&normalized) {
        normalized.insert(0, '_');
    }

    Ok(normalized)
}

/// Generates the documented movie filename using verified TMDB metadata.
pub fn generate_movie_filename(
    item: &TmdbItem,
    source_extension: &str,
) -> Result<String, NamingError> {
    ensure_media_type(item, MediaType::Movie)?;
    let title = normalized_item_title(item)?;
    if looks_like_series_marker(&title) {
        return Err(NamingError::AmbiguousMovieTitle);
    }

    let extension = parse_video_extension(source_extension)?;
    compose_filename(&format!("{} - ", item.id), &title, &extension)
}

/// Generates the documented series-episode filename using verified TMDB metadata.
pub fn generate_series_filename(
    item: &TmdbItem,
    episode: EpisodeRef,
    source_extension: &str,
) -> Result<String, NamingError> {
    ensure_media_type(item, MediaType::Series)?;
    let title = normalized_item_title(item)?;
    let extension = parse_video_extension(source_extension)?;
    let prefix = format!(
        "{} - S{:02}E{:02} - ",
        item.id,
        episode.season(),
        episode.episode()
    );

    compose_filename(&prefix, &title, &extension)
}

/// Parses one generated movie or series filename without using the filesystem or network.
pub fn parse_generated_filename(filename: &str) -> Result<ParsedMediaReference, NamingError> {
    if filename.is_empty() {
        return Err(invalid_filename("it is empty"));
    }
    if filename.len() > MAX_FILENAME_BYTES {
        return Err(invalid_filename(
            "it exceeds the supported filename length limit",
        ));
    }
    if filename
        .chars()
        .any(|character| character == '/' || character == '\\' || character.is_control())
    {
        return Err(invalid_filename(
            "it contains a path separator or control character",
        ));
    }

    let (stem, raw_extension) = filename
        .rsplit_once('.')
        .ok_or_else(|| invalid_filename("it has no video extension"))?;
    if stem.is_empty() || raw_extension.is_empty() {
        return Err(invalid_filename("its filename or extension is empty"));
    }
    let video_extension = parse_video_extension(raw_extension)?;

    let (raw_id, body) = stem
        .split_once(" - ")
        .ok_or_else(|| invalid_filename("it does not contain the required separator"))?;
    if raw_id.is_empty() || raw_id != raw_id.trim() {
        return Err(invalid_filename(
            "its TMDB ID is not a positive decimal value",
        ));
    }
    let tmdb_id = parse_filename_id(raw_id)?;
    if raw_id != tmdb_id.to_string() {
        return Err(invalid_filename(
            "its TMDB ID is not in canonical decimal form",
        ));
    }
    if body.is_empty() {
        return Err(invalid_filename("its title is empty"));
    }

    if looks_like_series_marker(body) {
        let (raw_marker, raw_title) = body
            .split_once(" - ")
            .ok_or_else(|| invalid_filename("its series marker has no title"))?;
        let episode = parse_series_marker(raw_marker)?;
        let title_hint = validate_parsed_title(raw_title)?;

        return Ok(ParsedMediaReference {
            tmdb_id,
            media_type: MediaType::Series,
            season: Some(episode.season()),
            episode: Some(episode.episode()),
            title_hint,
            video_extension,
        });
    }

    let title_hint = validate_parsed_title(body)?;
    Ok(ParsedMediaReference {
        tmdb_id,
        media_type: MediaType::Movie,
        season: None,
        episode: None,
        title_hint,
        video_extension,
    })
}

fn ensure_media_type(item: &TmdbItem, expected: MediaType) -> Result<(), NamingError> {
    if item.media_type == expected {
        Ok(())
    } else {
        Err(NamingError::MediaTypeMismatch {
            expected,
            actual: item.media_type,
        })
    }
}

fn normalized_item_title(item: &TmdbItem) -> Result<String, NamingError> {
    for candidate in std::iter::once(item.title.as_str()).chain(item.original_title.as_deref()) {
        if candidate.trim().is_empty() {
            continue;
        }

        if let Ok(title) = normalize_title_for_filename(candidate) {
            return Ok(title);
        }
    }

    Err(NamingError::EmptyTitle)
}

fn parse_video_extension(value: &str) -> Result<VideoExtension, NamingError> {
    let value_without_dot = value.strip_prefix('.').unwrap_or(value);
    VideoExtension::parse(value_without_dot).map_err(|error| match error {
        DomainError::UnsupportedVideoExtension { extension } => {
            NamingError::UnsupportedVideoExtension { extension }
        }
        _ => NamingError::UnsupportedVideoExtension {
            extension: sanitize_extension_for_error(value_without_dot),
        },
    })
}

fn compose_filename(
    prefix: &str,
    normalized_title: &str,
    extension: &VideoExtension,
) -> Result<String, NamingError> {
    let extension_suffix_bytes = extension.as_str().len() + 1;
    let fixed_bytes = prefix.len() + extension_suffix_bytes;
    if fixed_bytes >= MAX_FILENAME_BYTES {
        return Err(NamingError::FilenameTooLong);
    }

    let title_capacity = MAX_FILENAME_BYTES - fixed_bytes;
    let mut title = normalized_title.to_owned();
    if title.len() > title_capacity {
        truncate_to_bytes(&mut title, title_capacity);
        trim_trailing_filename_noise(&mut title);
        if title.is_empty() {
            return Err(NamingError::FilenameTooLong);
        }
        if is_windows_reserved_name(&title) {
            if title.len() + 1 > title_capacity {
                return Err(NamingError::FilenameTooLong);
            }
            title.insert(0, '_');
        }
    }

    let filename = format!("{prefix}{title}.{extension}");
    if filename.len() > MAX_FILENAME_BYTES {
        return Err(NamingError::FilenameTooLong);
    }
    Ok(filename)
}

fn validate_parsed_title(raw_title: &str) -> Result<String, NamingError> {
    if raw_title.is_empty() || raw_title != raw_title.trim() {
        return Err(invalid_filename("its title is not normalized"));
    }
    let normalized = normalize_title_for_filename(raw_title)
        .map_err(|_| invalid_filename("its title is empty or unsafe"))?;
    if normalized != raw_title {
        return Err(invalid_filename("its title is not normalized"));
    }
    Ok(raw_title.to_owned())
}

fn parse_filename_id(raw_id: &str) -> Result<TmdbId, NamingError> {
    crate::domain::parse_tmdb_id(raw_id)
        .map_err(|_| invalid_filename("its TMDB ID is not a positive decimal value"))
}

fn parse_series_marker(marker: &str) -> Result<EpisodeRef, NamingError> {
    let rest = marker
        .strip_prefix('S')
        .ok_or_else(|| invalid_filename("its series marker must use uppercase S"))?;
    let (raw_season, raw_episode) = rest
        .split_once('E')
        .ok_or_else(|| invalid_filename("its series marker must contain season and episode"))?;
    let season = parse_padded_number(raw_season, "season")?;
    let episode = parse_padded_number(raw_episode, "episode")?;
    Ok(EpisodeRef::new(season, episode))
}

fn parse_padded_number(value: &str, field: &'static str) -> Result<u32, NamingError> {
    if value.len() < 2 || !value.bytes().all(|byte| byte.is_ascii_digit()) {
        return Err(invalid_filename(match field {
            "season" => "its season is not a two-digit-or-longer decimal value",
            _ => "its episode is not a two-digit-or-longer decimal value",
        }));
    }
    value
        .parse::<u32>()
        .map_err(|_| invalid_filename("its season or episode is outside the supported range"))
}

fn looks_like_series_marker(value: &str) -> bool {
    let marker = value.split_once(" - ").map_or(value, |(marker, _)| marker);
    let Some(rest) = marker
        .strip_prefix('S')
        .or_else(|| marker.strip_prefix('s'))
    else {
        return false;
    };

    rest.starts_with(|character: char| character.is_ascii_digit())
        || ((rest.starts_with('E') || rest.starts_with('e'))
            && rest
                .chars()
                .nth(1)
                .is_some_and(|character| character.is_ascii_digit()))
}

fn is_invalid_title_character(character: char) -> bool {
    character.is_control()
        || matches!(
            character,
            '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|'
        )
}

fn trim_trailing_filename_noise(value: &mut String) {
    while matches!(value.chars().last(), Some(character) if character.is_whitespace() || character == '.' || character == '-')
    {
        value.pop();
    }
}

fn is_windows_reserved_name(value: &str) -> bool {
    let stem = value.split('.').next().unwrap_or(value);
    let uppercase = stem.to_ascii_uppercase();
    if matches!(uppercase.as_str(), "CON" | "PRN" | "AUX" | "NUL") {
        return true;
    }

    ["COM", "LPT"].iter().any(|prefix| {
        uppercase.strip_prefix(prefix).is_some_and(|suffix| {
            suffix.len() == 1
                && suffix
                    .bytes()
                    .next()
                    .is_some_and(|byte| byte.is_ascii_digit() && byte != b'0')
        })
    })
}

fn truncate_to_bytes(value: &mut String, max_bytes: usize) {
    while value.len() > max_bytes {
        value.pop();
    }
}

fn invalid_filename(reason: &'static str) -> NamingError {
    NamingError::InvalidGeneratedFilename { reason }
}

fn sanitize_extension_for_error(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character.is_control() {
                '�'
            } else {
                character
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::TmdbItem;

    fn movie(title: &str, original_title: Option<&str>) -> TmdbItem {
        TmdbItem {
            id: TmdbId::new(550).unwrap(),
            media_type: MediaType::Movie,
            title: title.to_owned(),
            original_title: original_title.map(ToOwned::to_owned),
            year: Some(1999),
        }
    }

    fn series(title: &str) -> TmdbItem {
        TmdbItem {
            id: TmdbId::new(1399).unwrap(),
            media_type: MediaType::Series,
            title: title.to_owned(),
            original_title: Some(title.to_owned()),
            year: Some(2011),
        }
    }

    #[test]
    fn title_normalization_replaces_invalid_characters_and_collapses_spacing() {
        let cases = [
            ("Mission: Impossible", "Mission - Impossible"),
            ("Spider-Man: No Way Home", "Spider-Man - No Way Home"),
            ("What?", "What"),
            ("Title / Director", "Title - Director"),
            ("Title \\ Director", "Title - Director"),
            ("Title * Director", "Title - Director"),
            (r#"Title " Director"#, "Title - Director"),
            ("Title < Director", "Title - Director"),
            ("Title > Director", "Title - Director"),
            ("Title | Director", "Title - Director"),
            ("  A   title  ", "A title"),
            ("Title::::Director", "Title - Director"),
            ("Title\0Director", "Title - Director"),
            ("ação 日本語", "ação 日本語"),
        ];

        for (raw, expected) in cases {
            assert_eq!(normalize_title_for_filename(raw).unwrap(), expected);
        }
    }

    #[test]
    fn title_normalization_is_idempotent_and_rejects_empty_results() {
        for title in [
            "Mission: Impossible",
            "Spider-Man: No Way Home",
            "Title / Director",
            "ação 日本語",
        ] {
            let normalized = normalize_title_for_filename(title).unwrap();
            assert_eq!(
                normalize_title_for_filename(&normalized).unwrap(),
                normalized
            );
        }

        for title in ["", "   ", "???", "...", "---", "\0\0"] {
            assert_eq!(
                normalize_title_for_filename(title),
                Err(NamingError::EmptyTitle)
            );
        }
    }

    #[test]
    fn title_normalization_avoids_windows_reserved_names() {
        for title in ["CON", "con.txt", "NUL.", "COM1", "LPT9"] {
            let normalized = normalize_title_for_filename(title).unwrap();
            assert!(
                normalized.starts_with('_'),
                "normalized title: {normalized}"
            );
            assert_eq!(
                normalize_title_for_filename(&normalized).unwrap(),
                normalized
            );
        }

        assert!(
            !normalize_title_for_filename("COM10")
                .unwrap()
                .starts_with('_')
        );
    }

    #[test]
    fn movie_filename_uses_localized_title_and_lowercase_source_extension() {
        let item = movie("Fight Club", Some("Fight Club"));

        assert_eq!(
            generate_movie_filename(&item, "MP4").unwrap(),
            "550 - Fight Club.mp4"
        );
    }

    #[test]
    fn movie_filename_falls_back_to_original_title_when_localized_title_is_unusable() {
        let item = movie("???", Some("Original Title"));

        assert_eq!(
            generate_movie_filename(&item, ".MKV").unwrap(),
            "550 - Original Title.mkv"
        );
    }

    #[test]
    fn series_filename_formats_episode_numbers_without_truncating_large_values() {
        let item = series("Game of Thrones");

        assert_eq!(
            generate_series_filename(&item, EpisodeRef::new(1, 2), "mKv").unwrap(),
            "1399 - S01E02 - Game of Thrones.mkv"
        );
        assert_eq!(
            generate_series_filename(&item, EpisodeRef::new(100, 123), "MP4").unwrap(),
            "1399 - S100E123 - Game of Thrones.mp4"
        );
    }

    #[test]
    fn filename_generation_rejects_wrong_media_type_and_unsupported_extensions() {
        let movie_item = movie("Fight Club", None);
        let series_item = series("Game of Thrones");

        assert!(matches!(
            generate_series_filename(&movie_item, EpisodeRef::new(1, 1), "mkv"),
            Err(NamingError::MediaTypeMismatch {
                expected: MediaType::Series,
                actual: MediaType::Movie,
            })
        ));
        assert!(matches!(
            generate_movie_filename(&series_item, "mkv"),
            Err(NamingError::MediaTypeMismatch {
                expected: MediaType::Movie,
                actual: MediaType::Series,
            })
        ));
        assert!(matches!(
            generate_movie_filename(&movie_item, "txt"),
            Err(NamingError::UnsupportedVideoExtension { .. })
        ));
    }

    #[test]
    fn movie_titles_that_look_like_series_prefixes_are_rejected_as_ambiguous() {
        for title in ["S01E01 - A Movie", "S01E01"] {
            let item = movie(title, None);

            assert_eq!(
                generate_movie_filename(&item, "mp4"),
                Err(NamingError::AmbiguousMovieTitle)
            );
        }
    }

    #[test]
    fn filename_generation_truncates_only_the_title_component() {
        let long_title = "A".repeat(400);
        let item = movie(&long_title, None);
        let filename = generate_movie_filename(&item, "mp4").unwrap();

        assert!(filename.len() <= MAX_FILENAME_BYTES);
        assert!(filename.starts_with("550 - "));
        assert!(filename.ends_with(".mp4"));
        let parsed = parse_generated_filename(&filename).unwrap();
        assert_eq!(parsed.tmdb_id.value(), 550);
        assert_eq!(parsed.media_type, MediaType::Movie);
    }

    #[test]
    fn generated_movie_filename_round_trips_through_parser() {
        let item = movie("Mission: Impossible", None);
        let generated = generate_movie_filename(&item, "MP4").unwrap();
        let parsed = parse_generated_filename(&generated).unwrap();

        assert_eq!(parsed.tmdb_id.value(), 550);
        assert_eq!(parsed.media_type, MediaType::Movie);
        assert_eq!(parsed.season, None);
        assert_eq!(parsed.episode, None);
        assert_eq!(parsed.title_hint, "Mission - Impossible");
        assert_eq!(parsed.extension(), "mp4");
    }

    #[test]
    fn generated_series_filename_round_trips_through_parser() {
        let item = series("Game of Thrones");
        let generated = generate_series_filename(&item, EpisodeRef::new(0, 7), "DVR-MS").unwrap();
        let parsed = parse_generated_filename(&generated).unwrap();

        assert_eq!(parsed.tmdb_id.value(), 1399);
        assert_eq!(parsed.media_type, MediaType::Series);
        assert_eq!(parsed.episode_ref(), Some(EpisodeRef::new(0, 7)));
        assert_eq!(parsed.title_hint, "Game of Thrones");
        assert_eq!(parsed.extension(), "dvr-ms");
    }

    #[test]
    fn parser_rejects_malformed_or_unsafe_generated_names() {
        for filename in [
            "",
            "550",
            "0 - Title.mp4",
            "-1 - Title.mp4",
            "550 - Title.txt",
            "550 - .mp4",
            "000550 - Title.mp4",
            "18446744073709551616 - Title.mp4",
            "550 - Mission: Impossible.mp4",
            "550 - Title/Director.mp4",
            "550 - S01 - Series.mp4",
            "550 - S1E02 - Series.mp4",
            "550 - S01E1 - Series.mp4",
            "550 - S01E02 - .mp4",
            "550 - s01e02 - Series.mp4",
            "550 - S01E02.mp4",
            "550 - Series.mp4/other",
        ] {
            assert!(
                parse_generated_filename(filename).is_err(),
                "expected `{filename}` to be rejected"
            );
        }
    }

    #[test]
    fn parser_accepts_case_insensitive_recognized_extensions_and_preserves_title_dots() {
        let parsed = parse_generated_filename("550 - WALL.E.MKV").unwrap();

        assert_eq!(parsed.title_hint, "WALL.E");
        assert_eq!(parsed.extension(), "mkv");
    }
}
